### ISSUE TITLE
Installation from PyPi fails on missing NumPy

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-preprocessing#11]
In a new virtual environment in WIN10 OS using Python 3.6, installation from PyPi, `pip install dwave-preprocessing` fails.

```
pip install dwave-preprocessing
Collecting dwave-preprocessing
  Using cached dwave-preprocessing-0.1.1.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jpasvolsky\!git_adtt\preprocessing\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jpasvolsky\\AppData\\Local\\Temp\\pip-install-7gz6g7t2\\dwave-preprocessing_e54f6ea941544163a14e1d3f0a31f300\\setup.py'"'"'; __file__='"'"'C:\\Users\\jpasvolsky\\AppData\\Local\\Temp\\pip-install-7gz6g7t2\\dwave-preprocessing_e54f6ea941544163a14e1d3f0a31f300\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jpasvolsky\AppData\Local\Temp\pip-pip-egg-info-6xezr56r'
         cwd: C:\Users\jpasvolsky\AppData\Local\Temp\pip-install-7gz6g7t2\dwave-preprocessing_e54f6ea941544163a14e1d3f0a31f300\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jpasvolsky\AppData\Local\Temp\pip-install-7gz6g7t2\dwave-preprocessing_e54f6ea941544163a14e1d3f0a31f300\setup.py", line 19, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/67/d3/dff294154297d936fe137230d03eb1d6b764dcf3bc06fbbfb8c6b85628ba/dwave-preprocessing-0.1.1.tar.gz#sha256=fb858610a630bbc087d481f6c36aa90039d24b0a20ed2bac4c14e7c39e2e8a8f (from https://pypi.org/simple/dwave-preprocessing/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached dwave-preprocessing-0.1.0.tar.gz (58 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jpasvolsky\!git_adtt\preprocessing\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jpasvolsky\\AppData\\Local\\Temp\\pip-install-7gz6g7t2\\dwave-preprocessing_98d156d7353845f1b61e9d394f16c5b1\\setup.py'"'"'; __file__='"'"'C:\\Users\\jpasvolsky\\AppData\\Local\\Temp\\pip-install-7gz6g7t2\\dwave-preprocessing_98d156d7353845f1b61e9d394f16c5b1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jpasvolsky\AppData\Local\Temp\pip-pip-egg-info-zu4d235f'
         cwd: C:\Users\jpasvolsky\AppData\Local\Temp\pip-install-7gz6g7t2\dwave-preprocessing_98d156d7353845f1b61e9d394f16c5b1\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jpasvolsky\AppData\Local\Temp\pip-install-7gz6g7t2\dwave-preprocessing_98d156d7353845f1b61e9d394f16c5b1\setup.py", line 19, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/66/6a/71ecc31e5dfca0a7c130946416cc29ed0c130f0e8c2f68ee59c8cae8a880/dwave-preprocessing-0.1.0.tar.gz#sha256=c90dba47d9294c05280b76a9f1cff6c9b3b2f28b3625d76421a5547a5f58f475 (from https://pypi.org/simple/dwave-preprocessing/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dwave-preprocessing (from versions: 0.1.0rc1, 0.1.0, 0.1.1rc1, 0.1.1rc2, 0.1.1)
ERROR: No matching distribution found for dwave-preprocessing
```

**Comment by arcondello** [comment]
Huh, I just noticed that the `pyproject.toml` is missing. Need to add that, and include it in the `MANIFEST.ini`
