### ISSUE TITLE
Wheel build fails due to circular dependency with dimod

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-preprocessing#28]
Building `dwave-preprocessing` from source (via PEP-517 build system), requires `dimod~=0.10.0`, which, in turn, in versions `>=0.10.5` requires `dwave-preprocessing>=0.3,<0.4`. As a result, `pip wheel` fails to install the (yet unreleased) version of `dwave-preprocessing`, and falls back to installing the latest for which it can find a wheel:

See for example [this build](https://app.circleci.com/pipelines/github/dwavesystems/dwave-preprocessing/41/workflows/d3859fe4-c975-4ec4-b822-ed63a2a329ab/jobs/819) of **0.3.1**:
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-e6b6j2px
Created temporary directory: /tmp/pip-req-tracker-ecez82nl
Initialized build tracking at /tmp/pip-req-tracker-ecez82nl
Created build tracker: /tmp/pip-req-tracker-ecez82nl
Entered build tracker: /tmp/pip-req-tracker-ecez82nl
Created temporary directory: /tmp/pip-wheel-lh7m08dq
Processing /dwave/preprocessing
  Created temporary directory: /tmp/pip-req-build-h47germ4
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Added file:///dwave/preprocessing to build tracker '/tmp/pip-req-tracker-ecez82nl'
  Created temporary directory: /tmp/pip-build-env-xmkbzxsj
  Created temporary directory: /tmp/pip-standalone-pip-9ifxkzl3
  Running command /opt/_internal/cpython-3.9.7/bin/python3.9 /tmp/pip-standalone-pip-9ifxkzl3/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-xmkbzxsj/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=46.4.0' 'wheel>=0.30.0' 'Cython>=0.29.21,<3.0' numpy==1.19.4 'dimod>=0.10.0.dev9,<0.11.0'
  Using pip 21.2.4 from /tmp/pip-standalone-pip-9ifxkzl3/__env_pip__.zip/pip (python 3.9)
  Collecting setuptools>=46.4.0
    Using cached setuptools-58.2.0-py3-none-any.whl (946 kB)
  Collecting wheel>=0.30.0
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting Cython<3.0,>=0.29.21
    Using cached Cython-0.29.24-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
  Collecting numpy==1.19.4
    Using cached numpy-1.19.4-cp39-cp39-manylinux1_x86_64.whl (13.4 MB)
  Collecting dimod<0.11.0,>=0.10.0.dev9
    Using cached dimod-0.10.7-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (10.6 MB)
  Collecting pyparsing<3.0.0,>=2.4.7
    Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
  Collecting dwave-preprocessing<0.4,>=0.3
    Using cached dwave-preprocessing-0.3.1.tar.gz (159 kB)
    Installing build dependencies: started
    Running command /opt/_internal/cpython-3.9.7/bin/python3.9 /tmp/pip-standalone-pip-9ifxkzl3/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-z40lauk3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=46.4.0' 'wheel>=0.30.0' 'Cython>=0.29.21,<3.0' numpy==1.19.4 'dimod>=0.10.0.dev9,<0.11.0'
    Collecting setuptools>=46.4.0
      Using cached setuptools-58.2.0-py3-none-any.whl (946 kB)
    Collecting wheel>=0.30.0
      Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
    Collecting Cython<3.0,>=0.29.21
      Using cached Cython-0.29.24-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
    Collecting numpy==1.19.4
      Using cached numpy-1.19.4-cp39-cp39-manylinux1_x86_64.whl (13.4 MB)
    Collecting dimod<0.11.0,>=0.10.0.dev9
      Using cached dimod-0.10.7-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (10.6 MB)
    Collecting pyparsing<3.0.0,>=2.4.7
      Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
    Collecting dwave-preprocessing<0.4,>=0.3
      Using cached dwave-preprocessing-0.3.1.tar.gz (159 kB)
    ERROR: Exception:
    Traceback (most recent call last):
      File "/tmp/pip-standalone-pip-9ifxkzl3/__env_pip__.zip/pip/_internal/cli/base_command.py", line 173, in _main
        status = self.run(options, args)
      ...
      File "/tmp/pip-standalone-pip-9ifxkzl3/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 97, in add
        raise LookupError(message)
    LookupError: https://files.pythonhosted.org/packages/9d/6e/51d3f843bafea371f3d96cf35a2e5c85e6d17c264cf3799ad6c11043c0c4/dwave-preprocessing-0.3.1.tar.gz#sha256=360e886a2e89f3f4aa0d3ddf448c71a2eaab74183000687bcafb1175682f8775 (from https://pypi.org/simple/dwave-preprocessing/) (requires-python:>=3.6) is already being built: dwave-preprocessing<0.4,>=0.3 from https://files.pythonhosted.org/packages/9d/6e/51d3f843bafea371f3d96cf35a2e5c85e6d17c264cf3799ad6c11043c0c4/dwave-preprocessing-0.3.1.tar.gz#sha256=360e886a2e89f3f4aa0d3ddf448c71a2eaab74183000687bcafb1175682f8775 (from dimod<0.11.0,>=0.10.0.dev9)
    Installing build dependencies: finished with status 'error'
  WARNING: Discarding https://files.pythonhosted.org/packages/9d/6e/51d3f843bafea371f3d96cf35a2e5c85e6d17c264cf3799ad6c11043c0c4/dwave-preprocessing-0.3.1.tar.gz#sha256=360e886a2e89f3f4aa0d3ddf448c71a2eaab74183000687bcafb1175682f8775 (from https://pypi.org/simple/dwave-preprocessing/) (requires-python:>=3.6). Command errored out with exit status 2: /opt/_internal/cpython-3.9.7/bin/python3.9 /tmp/pip-standalone-pip-9ifxkzl3/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-z40lauk3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=46.4.0' 'wheel>=0.30.0' 'Cython>=0.29.21,<3.0' numpy==1.19.4 'dimod>=0.10.0.dev9,<0.11.0' Check the logs for full command output.
    Using cached dwave_preprocessing-0.3.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (770 kB)
```

As a short-term fix, we can use `dimod<0.10.5` for building, but longer-term we should revisit the solution in https://github.com/dwavesystems/dimod/pull/999 to https://github.com/dwavesystems/dimod/issues/989.

**Comment by arcondello** [comment]
Closed by https://github.com/dwavesystems/dimod/pull/1056
